import turtle,time
alex = turtle.Turtle()
win = turtle.Screen()
win.title("my window")
win.bgcolor("black")
alex.color("violet")
alex.shape("turtle")
alex.forward(100)
time.sleep(1)
alex.left(90)
alex.forward(100)
time.sleep(1)
alex.left(90)
alex.forward(100)
time.sleep(1)
alex.left(90)
alex.forward(100)
